//! `.onnx` → `GraphIr` without ONNX Runtime.
//!
//! The models in `tests/models/` are generated by the `onnx` Python package
//! and the expected bytes are what `numpy_helper.to_array(t).tobytes()` says,
//! so the reference is the ONNX implementation and not our own reading of the
//! spec. `mixed.onnx` deliberately mixes the three storage forms — `raw_data`,
//! typed repeated fields, and narrow dtypes packed into `int32_data` — because
//! that is where a converter silently produces the wrong width.

use onnx_vulkan_core::{AttrValue, GraphIr};
use std::path::{Path, PathBuf};

fn models() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/models")
}

fn mixed() -> GraphIr {
    onnx_vulkan_frontend::load(models().join("mixed.onnx"))
        .expect("loading mixed.onnx")
        .graph
}

fn initializer<'a>(ir: &'a GraphIr, name: &str) -> &'a onnx_vulkan_core::InitializerIr {
    ir.initializers
        .get(name)
        .unwrap_or_else(|| panic!("initializer '{name}' missing"))
}

/// Every storage form must produce the same bytes that ONNX declares.
#[test]
fn every_storage_form_decodes_to_the_same_bytes_as_onnx() {
    let ir = mixed();

    // raw_data: already in the right layout
    assert_eq!(
        initializer(&ir, "w_raw").data,
        vec![0, 0, 192, 63, 0, 0, 32, 192, 0, 0, 0, 63, 0, 0, 64, 64]
    );
    // float_data
    assert_eq!(
        initializer(&ir, "w_typed").data,
        vec![0, 0, 128, 63, 0, 0, 0, 64, 0, 0, 64, 64]
    );
    // int64_data, with a negative one
    assert_eq!(
        initializer(&ir, "i64").data,
        vec![
            249, 255, 255, 255, 255, 255, 255, 255, 9, 0, 0, 0, 0, 0, 0, 0
        ]
    );

    // narrow dtypes all travel inside int32_data: the destination width comes
    // from the dtype, not from the field that carries them
    assert_eq!(initializer(&ir, "u8").data, vec![0, 1, 254, 255]);
    assert_eq!(initializer(&ir, "i8").data, vec![128, 0, 127]);
    assert_eq!(initializer(&ir, "bool_").data, vec![1, 0, 1]);
    assert_eq!(initializer(&ir, "f16").data, vec![192, 115, 0, 122]);
}

#[test]
fn dtype_and_shape_survive_the_conversion() {
    use onnx_vulkan_core::host_ops::{BOOL, FLOAT, INT8, INT64, UINT8};
    let ir = mixed();

    for (name, dtype, shape) in [
        ("w_raw", FLOAT, vec![2, 2]),
        ("w_typed", FLOAT, vec![3]),
        ("i64", INT64, vec![2]),
        ("u8", UINT8, vec![4]),
        ("i8", INT8, vec![3]),
        ("bool_", BOOL, vec![3]),
        ("f16", 10, vec![2]),
    ] {
        let init = initializer(&ir, name);
        assert_eq!(init.dtype, dtype, "dtype of {name}");
        assert_eq!(init.shape, shape, "shape of {name}");
    }
}

/// From IR version 4 an initializer may also appear among the graph inputs.
/// For the core, inputs are what the caller must provide, so a constant in
/// there would be a missing input at every run.
#[test]
fn initializers_are_not_reported_as_graph_inputs() {
    let ir = mixed();
    assert_eq!(ir.inputs, vec!["x".to_string()]);
    assert!(ir.initializers.contains_key("w_raw"));
    assert_eq!(ir.outputs, vec!["out".to_string()]);
}

#[test]
fn nodes_keep_order_names_and_optional_inputs() {
    let ir = mixed();
    let ops: Vec<&str> = ir.nodes.iter().map(|n| n.op.as_str()).collect();
    assert_eq!(ops, ["Constant", "MatMul", "Concat", "Clip", "LeakyRelu"]);

    let clip = &ir.nodes[3];
    assert_eq!(clip.name, "clip");
    // a missing optional input is an empty string, not a hole in the list:
    // the positions of subsequent inputs depend on this
    assert_eq!(clip.inputs, vec!["y", "", "hi"]);
}

/// A schema's version is not on the node: it is resolved from the opset the
/// model imports for the node's domain.
#[test]
fn schema_version_comes_from_the_model_opset() {
    let ir = mixed();
    for node in &ir.nodes {
        assert_eq!(node.since_version, 17, "node {}", node.name);
        assert_eq!(node.domain, "", "standard domain");
    }
}

#[test]
fn attributes_of_each_kind_are_converted() {
    let ir = mixed();
    let attr = |name: &str, key: &str| {
        ir.nodes
            .iter()
            .find(|n| n.name == name)
            .and_then(|n| n.attrs.get(key))
            .cloned()
    };

    assert_eq!(attr("cat", "axis"), Some(AttrValue::Int(1)));
    assert_eq!(attr("lrelu", "alpha"), Some(AttrValue::Float(0.125)));

    // the TENSOR attribute of `Constant` carries a complete initializer
    match attr("konst", "value") {
        Some(AttrValue::Tensor(t)) => {
            assert_eq!(t.shape, Vec::<i64>::new(), "scalar");
            assert_eq!(t.data, 6.0f32.to_le_bytes().to_vec());
        }
        other => panic!("expected a tensor, found {other:?}"),
    }
}

/// External weights are the normal form above 2 GB, and common well before:
/// they must produce exactly the same IR as the monolithic model.
#[test]
fn external_weights_produce_an_identical_ir() {
    let inline = mixed();
    let external = onnx_vulkan_frontend::load(models().join("external.onnx"))
        .expect("loading external.onnx")
        .graph;
    assert_eq!(external, inline);
}

/// Without knowing where the model comes from, external weights cannot be
/// resolved: an error is better than an empty tensor.
#[test]
fn external_weights_without_a_base_directory_are_refused() {
    let bytes = std::fs::read(models().join("external.onnx")).expect("read");
    match onnx_vulkan_frontend::load_from_bytes(&bytes, None) {
        Err(onnx_vulkan_frontend::Error::ExternalData(message)) => {
            assert!(
                message.contains("w_raw"),
                "the error must say which one: {message}"
            );
        }
        other => panic!("expected ExternalData, found {other:?}"),
    }
}

/// The frontend applies the same canonicalization as the EP: `axes` passed as
/// a constant input become an attribute again. If it did not, the same graph
/// would be covered for one path and uncovered for the other — and coverage is
/// what decides whether a model runs or fails hard.
#[test]
fn constant_parameters_are_folded_like_the_ort_path_does() {
    let ir = onnx_vulkan_frontend::load(models().join("reduce_axes_input.onnx"))
        .expect("loading")
        .graph;
    let node = &ir.nodes[0];

    assert_eq!(node.attrs.get("axes"), Some(&AttrValue::Ints(vec![1])));
    assert_eq!(node.inputs, vec!["x".to_string()], "input must be consumed");
    assert!(
        onnx_vulkan_core::is_implemented_node(node),
        "without canonicalization the node would not be claimable"
    );
}

#[test]
fn a_file_that_is_not_a_model_is_refused() {
    assert!(matches!(
        onnx_vulkan_frontend::load_from_bytes(b"this is not an ONNX protobuf", None),
        Err(onnx_vulkan_frontend::Error::Malformed(_))
    ));
}

// -------------------------------------------------------------- shape inference

/// The test that matters for shape inference: `shapes.onnx` is passed through
/// `onnx.shape_inference.infer_shapes(strict_mode=True)`, so it carries the
/// shape that **ONNX** deduces for every intermediate value. The frontend must
/// deduce the same, and `load` reports any divergence as a conflict. The
/// reference is again the ONNX implementation, not our own reading of the spec.
#[test]
fn inferred_shapes_agree_with_onnx_shape_inference() {
    let model =
        onnx_vulkan_frontend::load(models().join("shapes.onnx")).expect("loading shapes.onnx");
    assert!(
        model.conflicts.is_empty(),
        "divergences from ONNX shape inference: {:?}",
        model.conflicts
    );

    // an explicit sample, so the test fails saying *which* rule gave way
    // instead of a generic "no conflict"
    for (name, want) in [
        ("conv", vec![1, 8, 16, 16]),   // stride 2 with pad 1
        ("pooled", vec![1, 8, 8, 8]),   // MaxPool 2×2
        ("up", vec![1, 8, 16, 16]),     // Resize from `sizes`
        ("padded", vec![1, 8, 18, 18]), // Pad
        ("gap", vec![1, 8, 1, 1]),      // GlobalAveragePool
        ("flat", vec![1, 8]),           // Flatten
        ("gemm", vec![1, 4]),           // Gemm
        ("tr", vec![1, 18, 18, 8]),     // Transpose
        ("flat2", vec![1, 2592]),       // Reshape with -1
        ("sliced", vec![1, 6]),         // Slice
        ("tiled", vec![2, 6]),          // Tile
        ("red", vec![2, 1]),            // ReduceMean keepdims
        ("s0", vec![1, 4]),             // Split
        ("unsq", vec![1, 1, 4]),        // Unsqueeze
    ] {
        let got = model
            .types
            .get(name)
            .unwrap_or_else(|| panic!("value '{name}' without type"))
            .concrete();
        assert_eq!(got, Some(want), "shape of '{name}'");
    }
}

/// The dtype must be inferred even where it changes: `Cast`, comparisons,
/// `Shape`, and the second output of `TopK`.
#[test]
fn dtype_changes_are_tracked() {
    use onnx_vulkan_core::host_ops::{BOOL, FLOAT, INT64};
    let model = onnx_vulkan_frontend::load(models().join("shapes.onnx")).expect("loading");
    for (name, want) in [
        ("casted", INT64),
        ("gt", BOOL),
        ("shp", INT64),
        ("ti", INT64),
        ("tv", FLOAT),
    ] {
        assert_eq!(
            model.types.get(name).and_then(|t| t.dtype),
            Some(want),
            "dtype of '{name}'"
        );
    }
    // `Shape` of a rank-4 tensor is a 4-element vector, known even without
    // knowing the dimensions
    assert_eq!(
        model.types.get("shp").and_then(|t| t.concrete()),
        Some(vec![4])
    );
}

/// A symbolic dimension is not an unknown dimension: it propagates, and two
/// occurrences of the same symbol stay the same value.
#[test]
fn symbolic_dimensions_propagate() {
    use onnx_vulkan_frontend::Dim;
    let model = onnx_vulkan_frontend::load(models().join("mixed.onnx")).expect("loading");
    // in mixed.onnx everything is fixed: here it is enough that the declared
    // input arrives
    assert_eq!(
        model.input_type("x").and_then(|t| t.concrete()),
        Some(vec![2, 2])
    );
    assert_ne!(Dim::Symbol("batch".into()), Dim::Unknown);
}
