//! Raw bindgen bindings for ONNX Runtime 1.27.1 C headers:
//! `onnxruntime_c_api.h` + `onnxruntime_ep_c_api.h`.
//!
//! Generated by `build.rs`; requires headers downloaded via
//! `scripts/fetch-deps.sh` (o `ORT_INCLUDE_DIR`).

#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(unsafe_op_in_unsafe_fn)]
#![allow(clippy::all)]

include!(concat!(env!("OUT_DIR"), "/bindings.rs"));
