//! `Resize` with `mode = cubic`, the Keys 4×4 kernel.
//!
//! The expected values are **not** recomputed here from a second reading of
//! the spec: they come from `onnx.reference.ReferenceEvaluator` on the same
//! graph (opset 17, `cubic_coeff_a = -0.75`, `exclude_outside = 0`). This is
//! a comparison with the ONNX reference implementation, not with itself.

use onnx_vulkan_core::host_ops::{FLOAT, HostTensor};
use onnx_vulkan_core::{
    AttrValue, ExecutionEnv, GraphIr, InitializerIr, KernelCache, NodeIr, Tensor, execute,
    is_implemented_node,
};
use std::collections::HashMap;
use vk_compute::VkContext;

/// [1, 1, 3, 4], generated by the `pseudo()` used in the other tests.
const X: [f32; 12] = [
    -0.029986585,
    0.2904268,
    -0.37564376,
    0.114317395,
    -0.73784435,
    -0.19062829,
    -0.3968176,
    0.65281945,
    0.9065083,
    -0.11145001,
    0.7678919,
    0.50345314,
];

/// ONNX reference for `coordinate_transformation_mode = half_pixel`.
const HALF_PIXEL: [f32; 48] = [
    0.013399566,
    0.13696617,
    0.34935412,
    0.19538821,
    -0.24654137,
    -0.35114256,
    -0.065232694,
    0.1029722,
    -0.2931865,
    -0.13037235,
    0.14523749,
    0.06441653,
    -0.3403569,
    -0.3344714,
    0.07027567,
    0.31149456,
    -0.8206033,
    -0.5862243,
    -0.19491647,
    -0.1538606,
    -0.50731367,
    -0.31919134,
    0.29115158,
    0.65851617,
    -0.4627894,
    -0.3939984,
    -0.28179067,
    -0.20910355,
    -0.23308352,
    0.057866547,
    0.49514675,
    0.7613031,
    0.57819563,
    0.33775425,
    -0.06632676,
    -0.07011634,
    0.32747415,
    0.58377546,
    0.56706387,
    0.56181103,
    1.2047094,
    0.7769653,
    0.060114097,
    0.011461638,
    0.66648364,
    0.9042384,
    0.61395115,
    0.4451923,
];

/// ONNX reference for `coordinate_transformation_mode = asymmetric`.
const ASYMMETRIC: [f32; 48] = [
    -0.029986585,
    0.19266422,
    0.2904268,
    -0.05850359,
    -0.37564376,
    -0.19310729,
    0.114317395,
    0.16025126,
    -0.53807354,
    -0.19737063,
    0.042476285,
    -0.25576457,
    -0.49542218,
    -0.09935332,
    0.3975715,
    0.48128968,
    -0.73784435,
    -0.4449061,
    -0.19062829,
    -0.3408249,
    -0.3968176,
    0.10867068,
    0.65281945,
    0.7512229,
    0.017970324,
    -0.12467982,
    -0.19613807,
    -0.06809084,
    0.1835521,
    0.44168243,
    0.62862086,
    0.6703461,
    0.9065083,
    0.31509086,
    -0.11145001,
    0.25757846,
    0.7678919,
    0.7181108,
    0.50345314,
    0.478662,
    1.0606664,
    0.38634056,
    -0.10402705,
    0.3136788,
    0.8770834,
    0.77524585,
    0.48945004,
    0.4531094,
];

fn node(attrs: &[(&str, AttrValue)]) -> NodeIr {
    NodeIr {
        domain: String::new(),
        op: "Resize".to_string(),
        since_version: 13,
        name: "Resize_0".to_string(),
        inputs: vec!["x".to_string(), String::new(), "scales".to_string()],
        outputs: vec!["out".to_string()],
        attrs: attrs
            .iter()
            .map(|(k, v)| ((*k).to_string(), v.clone()))
            .collect(),
    }
}

fn run(coord: &str) -> (Vec<f32>, Vec<i64>) {
    let ir = GraphIr {
        nodes: vec![node(&[
            ("mode", AttrValue::String("cubic".to_string())),
            (
                "coordinate_transformation_mode",
                AttrValue::String(coord.to_string()),
            ),
            ("cubic_coeff_a", AttrValue::Float(-0.75)),
        ])],
        initializers: HashMap::from([(
            "scales".to_string(),
            InitializerIr {
                dtype: FLOAT,
                shape: vec![4],
                data: [1.0f32, 1.0, 2.0, 2.0]
                    .iter()
                    .flat_map(|v| v.to_le_bytes())
                    .collect(),
            },
        )]),
        inputs: vec!["x".to_string()],
        outputs: vec!["out".to_string()],
    };

    let context = VkContext::new().expect("Vulkan context");
    let cache = KernelCache::new(&context);
    let mut env = ExecutionEnv::new(&cache, &ir.initializers);
    env.set(
        "x",
        Tensor::Host(HostTensor::from_f32(vec![1, 1, 3, 4], &X)),
    );
    execute(&ir, &mut env).expect("graph execution");
    let out = env.host("out").expect("output on host").clone();
    env.finish();
    (out.to_f32().expect("output f32"), out.shape)
}

fn assert_close(got: &[f32], want: &[f32]) {
    assert_eq!(got.len(), want.len(), "different lengths");
    for (i, (g, w)) in got.iter().zip(want).enumerate() {
        assert!(
            (g - w).abs() <= 1e-5 + 1e-4 * w.abs(),
            "element {i}: {g} != {w}"
        );
    }
}

#[test]
fn cubic_half_pixel_matches_onnx_reference() {
    let (got, shape) = run("half_pixel");
    assert_eq!(shape, vec![1, 1, 6, 8]);
    assert_close(&got, &HALF_PIXEL);
}

#[test]
fn cubic_asymmetric_matches_onnx_reference() {
    let (got, shape) = run("asymmetric");
    assert_eq!(shape, vec![1, 1, 6, 8]);
    assert_close(&got, &ASYMMETRIC);
}

/// `exclude_outside = 1` would zero and renormalize the out-of-bounds weights:
/// not implemented, so the node must not be claimed.
#[test]
fn exclude_outside_is_not_claimed() {
    assert!(
        is_implemented_node(&node(&[("mode", AttrValue::String("cubic".to_string()))])),
        "cubic is implemented"
    );
    assert!(
        !is_implemented_node(&node(&[
            ("mode", AttrValue::String("cubic".to_string())),
            ("exclude_outside", AttrValue::Int(1)),
        ])),
        "exclude_outside = 1 not implemented"
    );
}
